#!/usr/bin/env bash

# This is a tiny wrapper around pre-command which logs the resultant environment
# so that the test can assert against it.

set -euo pipefail

# Reminder, this has to be sourced so that it can change the environment of the
# current process so that the next line can work
source pre-command &>/dev/null

# I don't really know what this command does, but I couldn't quite get awk to do
# what I wanted and after a few rounds with ChatGPT that did nothing, this
# appears to work.
env | sed -n '/^CHECK_RUN_REPORTER_TESTS_FOR_THIS_AGENT=/,/^.*$/p'
