#!/usr/bin/env bash

set -euo pipefail
shopt -s globstar nullglob

HOOKS_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
PATH="$PATH:$HOOKS_DIR/../bin"

find_root () {
  if echo "$BUILDKITE_PLUGINS" | grep -q docker-compose-buildkite-plugin; then
    log 'It looks like this step was run via Docker Compose.'
    ROOT=''
    if [ -f Dockerfile ]; then
      log 'Attempting to parse Dockerfile'
      ROOT="$(awk '/WORKDIR/ {print $2}' Dockerfile | tail -n 1)"
    else
      log 'No Dockerfile found.'
    fi

    if [ "$ROOT" == '' ]; then
      log 'Could not determine root from Dockerfile. Assuming "/" for root.'
      echo '/'
    else
      echo "$ROOT"
    fi
  elif echo "$BUILDKITE_PLUGINS" | grep -q docker-buildkite-plugin; then
    log 'It looks like this step was run via Docker.'

    if [ "${BUILDKITE_PLUGIN_DOCKER_WORKDIR:-}" != '' ]; then
      log 'Using the configured docker plugin workdir'
      echo "$BUILDKITE_PLUGIN_DOCKER_WORKDIR"
    else
      log 'Using the default docker plugin workdir'
      echo '/workdir'
    fi
  else
    log 'It looks like this step was run right on the agent. Using PWD for root'
    pwd
  fi
}

log () {
  echo "$@" 1>&2
}

HOSTNAME=${BUILDKITE_PLUGIN_CHECK_RUN_REPORTER_HOSTNAME:-''}
LABEL=${BUILDKITE_PLUGIN_CHECK_RUN_REPORTER_LABEL:-$BUILDKITE_LABEL}
ROOT=${BUILDKITE_PLUGIN_CHECK_RUN_REPORTER_ROOT:-$(find_root)}
SHA=$BUILDKITE_COMMIT
TOKEN=$BUILDKITE_PLUGIN_CHECK_RUN_REPORTER_TOKEN
REPORT_DIR=$BUILDKITE_PLUGIN_CHECK_RUN_REPORTER_REPORT

log 'Running check-run-reporter-buildkite-plugin with the following parameters'
log "LABEL=$LABEL"
log "ROOT=$ROOT"
log "SHA=$SHA"

echo "Uploading reports to Check Run Reporter"

BIN=
if [ "$(uname)" == "Darwin" ]; then
  BIN=crr-macos
else
  BIN=crr-linux
fi

$BIN submit \
  --hostname="$HOSTNAME" \
  --label="$LABEL" \
  --report="$REPORT_DIR" \
  --root="$ROOT" \
  --sha="$SHA" \
  --token="$TOKEN"

echo "Uploaded reports to Check Run Reporter"
